#!/bin/bash
cd `dirname $0`

export LD_LIBRARY_PATH=../dist/lib

if test -z $1
then {
    export VARIANTS=debug
} else {
    export VARIANTS=$1
}
fi

if ../bjam -j`grep -c ^processor /proc/cpuinfo` toolset=gcc $VARIANTS
then {
    echo fost-postgres OK
    exit 0
} else {
    exit 1
}
fi
