#!/bin/bash
cd `dirname $0`

export LD_LIBRARY_PATH=../dist/lib

if test -z $1
then {
    export VARIANTS=debug
} else {
    export VARIANTS=$1
}
fi

if ../bjam -j`grep -c ^processor /proc/cpuinfo` toolset=gcc $VARIANTS
then {
    if ../dist/bin/fost-schema-test-dyndriver pqxx libfost-postgres.so \
        -d "user=Test password=tester host=localhost dbname=postgres"
    then {
        echo fost-postgres OK
    } else {
        exit 1
    }
    fi
} else {
    exit 1
}
fi
